{{- if not .Values.server.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simplex-smp.fullname" . }}
  labels:
    {{- include "simplex-smp.labels" . | nindent 4 }}
type: Opaque
stringData:
  PASS: {{ .Values.server.password | quote }}
{{- end }}

